// <auto-generated />
using System;
using Chronicle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chronicle.Data.Migrations
{
    [DbContext(typeof(ChronicleDbContext))]
    [Migration("20260825144113_AddIsApproximateTimestampToInteractionEvent")]
    partial class AddIsApproximateTimestampToInteractionEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("Chronicle.Core.Models.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("api_tokens", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.BackgroundTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastRunSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunConfirmationMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunConfirmationTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Schedulable")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("PluginId");

                    b.ToTable("background_tasks", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.DeviceAuthCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApiTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("device_auth_codes", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.InteractionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproximateTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MarkedAsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Timestamp");

                    b.HasIndex("UserId", "MediaItemId", "Timestamp")
                        .IsUnique();

                    b.ToTable("interaction_events", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BillingOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("billing_order");

                    b.Property<string>("CharacterName")
                        .HasColumnType("TEXT")
                        .HasColumnName("character_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalPersonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_person_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("person_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("idx_media_credits_item");

                    b.HasIndex("PersonName")
                        .HasDatabaseName("idx_media_credits_person");

                    b.ToTable("media_credits", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Source");

                    b.HasIndex("Source", "ExternalId");

                    b.ToTable("media_external_ids", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStub")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("idx_media_items_normalized_name");

                    b.HasIndex("ParentId");

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .HasDatabaseName("idx_aliases_alias");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("idx_aliases_media_item_id");

                    b.ToTable("media_item_aliases", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<int>("ItemAId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_a_id");

                    b.Property<int>("ItemBId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_b_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemBId");

                    b.HasIndex("ItemAId", "ItemBId")
                        .IsUnique()
                        .HasDatabaseName("idx_dup_candidates_unique");

                    b.ToTable("media_item_duplicate_candidates", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("dismissed_at");

                    b.Property<int>("ItemAId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_a_id");

                    b.Property<int>("ItemBId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_b_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemBId");

                    b.HasIndex("ItemAId", "ItemBId")
                        .IsUnique()
                        .HasDatabaseName("idx_dup_dismissals_unique");

                    b.ToTable("media_item_duplicate_dismissals", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemEnrichment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "PluginId")
                        .IsUnique();

                    b.ToTable("media_enrichment", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemMerge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("LoserChildIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("loser_child_ids_json");

                    b.Property<string>("LoserExternalIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("loser_external_ids_json");

                    b.Property<int>("LoserHierarchyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loser_hierarchy_level");

                    b.Property<int>("LoserMediaTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loser_media_type_id");

                    b.Property<string>("LoserMetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("loser_metadata_json");

                    b.Property<string>("LoserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("loser_name");

                    b.Property<int?>("LoserNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loser_number");

                    b.Property<int>("LoserOriginalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loser_original_id");

                    b.Property<int?>("LoserParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loser_parent_id");

                    b.Property<int?>("LoserYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loser_year");

                    b.Property<DateTime>("MergedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("merged_at");

                    b.Property<int?>("MergedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("merged_by_user_id");

                    b.Property<int>("WinnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("idx_merges_winner_id");

                    b.ToTable("media_item_merges", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("media_lists", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("ListId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("media_list_items", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HierarchyLabels")
                        .HasColumnType("TEXT");

                    b.Property<int>("HierarchyLevels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InteractionVerb")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("watched");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("minutes");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("media_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Television series, seasons, and episodes",
                            DisplayName = "TV Shows",
                            HierarchyLabels = "Show,Season,Episode",
                            HierarchyLevels = 3,
                            InteractionVerb = "watched",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "tv",
                            ProgressUnit = "minutes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Feature films and short films",
                            DisplayName = "Movies",
                            HierarchyLabels = "Movie",
                            HierarchyLevels = 1,
                            InteractionVerb = "watched",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "movies",
                            ProgressUnit = "minutes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Artists, albums, and tracks",
                            DisplayName = "Music",
                            HierarchyLabels = "Artist,Album,Track",
                            HierarchyLevels = 3,
                            InteractionVerb = "listened",
                            IsActive = true,
                            IsBuiltIn = true,
                            Name = "music",
                            ProgressUnit = "tracks"
                        });
                });

            modelBuilder.Entity("Chronicle.Core.Models.Plugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandColorDark")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandColorLight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DllPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixMatchHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstalledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginId")
                        .IsUnique();

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.ScanFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recursive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("scan_folders", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("preferences_json");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Handle");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind");

                    b.ToTable("user_contacts", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ResumePositionPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ResumeUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("user_libraries", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.ApiToken", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.BackgroundTask", b =>
                {
                    b.HasOne("Chronicle.Core.Models.Plugin", "Plugin")
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .HasPrincipalKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("Chronicle.Core.Models.DeviceAuthCode", b =>
                {
                    b.HasOne("Chronicle.Core.Models.ApiToken", "ApiToken")
                        .WithMany()
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.InteractionEvent", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaCredit", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaExternalId", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany("ExternalIds")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItem", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MediaType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemAlias", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany("Aliases")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateCandidate", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "ItemA")
                        .WithMany()
                        .HasForeignKey("ItemAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "ItemB")
                        .WithMany()
                        .HasForeignKey("ItemBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemA");

                    b.Navigation("ItemB");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateDismissal", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("ItemAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("ItemBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemEnrichment", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemMerge", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "Winner")
                        .WithMany("MergesAsWinner")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaList", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaListItem", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.ScanFolder", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserContact", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserLibrary", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItem", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Children");

                    b.Navigation("ExternalIds");

                    b.Navigation("MergesAsWinner");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Chronicle.Core.Models.User", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
