// <auto-generated />
using System;
using Chronicle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronicle.Data.Postgres.Migrations
{
    [DbContext(typeof(ChronicleDbContext))]
    partial class ChronicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronicle.Core.Models.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("full");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("api_tokens", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.BackgroundTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("LastRunSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PluginId")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RunConfirmationMessage")
                        .HasColumnType("text");

                    b.Property<string>("RunConfirmationTitle")
                        .HasColumnType("text");

                    b.Property<bool>("Schedulable")
                        .HasColumnType("boolean");

                    b.HasKey("TaskId");

                    b.HasIndex("PluginId");

                    b.ToTable("background_tasks", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.DeviceAuthCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiTokenId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawApiKey")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("device_auth_codes", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.InteractionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproximateTimestamp")
                        .HasColumnType("boolean");

                    b.Property<bool>("MarkedAsWatched")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Timestamp");

                    b.HasIndex("UserId", "MediaItemId", "Timestamp")
                        .IsUnique();

                    b.ToTable("interaction_events", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.KodiDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("api_token_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenId")
                        .IsUnique()
                        .HasDatabaseName("idx_kodi_devices_api_token");

                    b.HasIndex("UserId");

                    b.ToTable("kodi_devices", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.KodiLibraryId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("KodiDeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("kodi_device_id");

                    b.Property<int>("KodiId")
                        .HasColumnType("integer")
                        .HasColumnName("kodi_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("media_item_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("KodiDeviceId", "MediaItemId")
                        .IsUnique()
                        .HasDatabaseName("idx_kodi_library_ids_unique");

                    b.ToTable("kodi_library_ids", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.KodiScanAck", b =>
                {
                    b.Property<int>("ApiTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("api_token_id");

                    b.Property<DateTime?>("LastAckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ack_at");

                    b.HasKey("ApiTokenId");

                    b.ToTable("kodi_scan_acks", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingOrder")
                        .HasColumnType("integer")
                        .HasColumnName("billing_order");

                    b.Property<string>("CharacterName")
                        .HasColumnType("text")
                        .HasColumnName("character_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalPersonId")
                        .HasColumnType("text")
                        .HasColumnName("external_person_id");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("media_item_id");

                    b.Property<int?>("PersonMediaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("person_media_item_id");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("person_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("idx_media_credits_item");

                    b.HasIndex("PersonMediaItemId")
                        .HasDatabaseName("idx_media_credits_person_item");

                    b.HasIndex("PersonName")
                        .HasDatabaseName("idx_media_credits_person");

                    b.HasIndex("Role", "PersonMediaItemId")
                        .HasDatabaseName("idx_media_credits_role");

                    b.ToTable("media_credits", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Source");

                    b.HasIndex("Source", "ExternalId");

                    b.ToTable("media_external_ids", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStub")
                        .HasColumnType("boolean");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<string>("NormalizedNameLoose")
                        .HasColumnType("text")
                        .HasColumnName("normalized_name_loose");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<double?>("SeriesPosition")
                        .HasColumnType("double precision");

                    b.Property<string>("SortName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("idx_media_items_normalized_name");

                    b.HasIndex("NormalizedNameLoose")
                        .HasDatabaseName("idx_media_items_normalized_name_loose");

                    b.HasIndex("ParentId");

                    b.HasIndex("NormalizedName", "MediaTypeId")
                        .HasDatabaseName("idx_media_items_normalized_name_mediatypeid");

                    b.HasIndex("NormalizedNameLoose", "MediaTypeId")
                        .HasDatabaseName("idx_media_items_normalized_name_loose_mediatypeid");

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("media_item_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .HasDatabaseName("idx_aliases_alias");

                    b.HasIndex("MediaItemId")
                        .HasDatabaseName("idx_aliases_media_item_id");

                    b.ToTable("media_item_aliases", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int>("ItemAId")
                        .HasColumnType("integer")
                        .HasColumnName("item_a_id");

                    b.Property<int>("ItemBId")
                        .HasColumnType("integer")
                        .HasColumnName("item_b_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemBId");

                    b.HasIndex("ItemAId", "ItemBId")
                        .IsUnique()
                        .HasDatabaseName("idx_dup_candidates_unique");

                    b.ToTable("media_item_duplicate_candidates", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<int>("ItemAId")
                        .HasColumnType("integer")
                        .HasColumnName("item_a_id");

                    b.Property<int>("ItemBId")
                        .HasColumnType("integer")
                        .HasColumnName("item_b_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemBId");

                    b.HasIndex("ItemAId", "ItemBId")
                        .IsUnique()
                        .HasDatabaseName("idx_dup_dismissals_unique");

                    b.ToTable("media_item_duplicate_dismissals", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemEnrichment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "PluginId")
                        .IsUnique();

                    b.ToTable("media_enrichment", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemKnownFileName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("NOCASE");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.HasIndex("MediaItemId", "FileName")
                        .IsUnique();

                    b.ToTable("media_item_known_file_names", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemMerge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoserChildIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("loser_child_ids_json");

                    b.Property<string>("LoserExternalIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("loser_external_ids_json");

                    b.Property<int>("LoserHierarchyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("loser_hierarchy_level");

                    b.Property<int>("LoserMediaTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("loser_media_type_id");

                    b.Property<string>("LoserMetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("loser_metadata_json");

                    b.Property<string>("LoserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loser_name");

                    b.Property<int?>("LoserNumber")
                        .HasColumnType("integer")
                        .HasColumnName("loser_number");

                    b.Property<int>("LoserOriginalId")
                        .HasColumnType("integer")
                        .HasColumnName("loser_original_id");

                    b.Property<int?>("LoserParentId")
                        .HasColumnType("integer")
                        .HasColumnName("loser_parent_id");

                    b.Property<double?>("LoserSeriesPosition")
                        .HasColumnType("double precision")
                        .HasColumnName("loser_series_position");

                    b.Property<int?>("LoserYear")
                        .HasColumnType("integer")
                        .HasColumnName("loser_year");

                    b.Property<DateTime>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<int?>("MergedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("merged_by_user_id");

                    b.Property<int>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("idx_merges_winner_id");

                    b.ToTable("media_item_merges", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemRelatedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MissingSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "Path")
                        .IsUnique();

                    b.ToTable("media_item_related_files", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("media_lists", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("ListId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("media_list_items", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CastHeading")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HierarchyLabels")
                        .HasColumnType("text");

                    b.Property<int>("HierarchyLevels")
                        .HasColumnType("integer");

                    b.Property<string>("InteractionVerb")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("watched");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrackable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsUserModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProgressUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("minutes");

                    b.Property<string>("ProviderFamily")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ScanHintsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ScanStrategy")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("SupportsCollections")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("media_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Television series, seasons, and episodes",
                            DisplayName = "TV Shows",
                            HierarchyLabels = "Show,Season,Episode",
                            HierarchyLevels = 3,
                            InteractionVerb = "watched",
                            IsActive = true,
                            IsBuiltIn = true,
                            IsTrackable = true,
                            IsUserModified = false,
                            Name = "tv",
                            ProgressUnit = "minutes",
                            ProviderFamily = "tv",
                            SupportsCollections = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Feature films and short films",
                            DisplayName = "Movies",
                            HierarchyLabels = "Movie",
                            HierarchyLevels = 1,
                            InteractionVerb = "watched",
                            IsActive = true,
                            IsBuiltIn = true,
                            IsTrackable = true,
                            IsUserModified = false,
                            Name = "movies",
                            ProgressUnit = "minutes",
                            ProviderFamily = "movie",
                            SupportsCollections = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Artists, albums, and tracks",
                            DisplayName = "Music",
                            HierarchyLabels = "Artist,Album,Track",
                            HierarchyLevels = 3,
                            InteractionVerb = "listened",
                            IsActive = true,
                            IsBuiltIn = true,
                            IsTrackable = true,
                            IsUserModified = false,
                            Name = "music",
                            ProgressUnit = "tracks",
                            ProviderFamily = "music",
                            SupportsCollections = false
                        });
                });

            modelBuilder.Entity("Chronicle.Core.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind", "DedupeKey");

                    b.HasIndex("UserId", "ReadAt", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Delivery")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.PersonHeadshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<int>("PersonMediaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("person_media_item_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PersonMediaItemId")
                        .HasDatabaseName("idx_person_headshots_person");

                    b.HasIndex("PersonMediaItemId", "Url")
                        .IsUnique()
                        .HasDatabaseName("idx_person_headshots_unique");

                    b.ToTable("person_headshots", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.PersonProviderCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .HasColumnType("text")
                        .HasColumnName("character_name");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<int>("PersonMediaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("person_media_item_id");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("PersonMediaItemId", "Source", "ExternalId", "Role")
                        .IsUnique()
                        .HasDatabaseName("idx_person_provider_credits_unique");

                    b.ToTable("person_provider_credits", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.Plugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BrandColorDark")
                        .HasColumnType("text");

                    b.Property<string>("BrandColorLight")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DllPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FilesChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilesSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FixMatchHint")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("InstalledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("IntegrityBlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LatestVersionAvailable")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviousFilesSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PluginId")
                        .IsUnique();

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.ScanFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BundleRelatedFiles")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MediaTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Recursive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("scan_folders", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Handle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("preferences_json");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Handle");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind");

                    b.ToTable("user_contacts", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastKnownProgressAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LastKnownProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("ResumePositionPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ResumeUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UserRatingUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WatchResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("user_libraries", (string)null);
                });

            modelBuilder.Entity("Chronicle.Core.Models.ApiToken", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.BackgroundTask", b =>
                {
                    b.HasOne("Chronicle.Core.Models.Plugin", "Plugin")
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .HasPrincipalKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("Chronicle.Core.Models.DeviceAuthCode", b =>
                {
                    b.HasOne("Chronicle.Core.Models.ApiToken", "ApiToken")
                        .WithMany()
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.InteractionEvent", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.KodiDevice", b =>
                {
                    b.HasOne("Chronicle.Core.Models.ApiToken", null)
                        .WithMany()
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chronicle.Core.Models.KodiLibraryId", b =>
                {
                    b.HasOne("Chronicle.Core.Models.KodiDevice", null)
                        .WithMany()
                        .HasForeignKey("KodiDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chronicle.Core.Models.KodiScanAck", b =>
                {
                    b.HasOne("Chronicle.Core.Models.ApiToken", null)
                        .WithMany()
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaCredit", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "PersonMediaItem")
                        .WithMany()
                        .HasForeignKey("PersonMediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaItem");

                    b.Navigation("PersonMediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaExternalId", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany("ExternalIds")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItem", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MediaType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemAlias", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany("Aliases")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateCandidate", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "ItemA")
                        .WithMany()
                        .HasForeignKey("ItemAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "ItemB")
                        .WithMany()
                        .HasForeignKey("ItemBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemA");

                    b.Navigation("ItemB");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemDuplicateDismissal", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("ItemAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("ItemBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemEnrichment", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemKnownFileName", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany("KnownFileNames")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemMerge", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "Winner")
                        .WithMany("MergesAsWinner")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItemRelatedFile", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaList", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaListItem", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.Notification", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.PersonHeadshot", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "PersonMediaItem")
                        .WithMany()
                        .HasForeignKey("PersonMediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonMediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.PersonProviderCredit", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "PersonMediaItem")
                        .WithMany()
                        .HasForeignKey("PersonMediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonMediaItem");
                });

            modelBuilder.Entity("Chronicle.Core.Models.ScanFolder", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserContact", b =>
                {
                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.UserLibrary", b =>
                {
                    b.HasOne("Chronicle.Core.Models.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicle.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaItem", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Children");

                    b.Navigation("ExternalIds");

                    b.Navigation("KnownFileNames");

                    b.Navigation("MergesAsWinner");
                });

            modelBuilder.Entity("Chronicle.Core.Models.MediaList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Chronicle.Core.Models.User", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
