<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Chronicle.Plugin.Trakt</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Chronicle.Plugins\Chronicle.Plugins.csproj" />
  </ItemGroup>

</Project>
